name: Lint Code Base
on:
  push:
    branches-ignore: [scratch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Lint
        uses: azohra/shell-linter@latest
